### PR TITLE
Fix copyfour_jp

### PR DESCRIPTION
**Pull request by pixyzehn**
I made copyfour_jp natural Japanese.

### CODE REVIEW

**Comment by pietbrauer** [comment]
Honestly, I can't judge the PullRequests 😁. This was done by @modocache maybe he has thoughts on that? It's for the Screenshots and looks like this in English and Japanese:

5 5inch_screenshot4_en
5 5inch_screenshot4_jp

**Comment by modocache** [comment]
@pixyzehn's is definitely better 💯

**Comment by pietbrauer** [comment]
@modocache Thanks! Does this count for #4 and #3 as well?

**Comment by modocache** [comment]
Yup!

**Comment by pietbrauer** [comment]
@pixyzehn and @modocache Thanks a lot for your efforts, your improvements made it into the 1.9.2 App Store Page. Can't thank you enough.

screen shot 2016-10-02 at 13 07 30

**Comment by pixyzehn** [comment]
Looks good. I hope many Japanese use it.

**Pull request merged**
